BINANCE_API_URL = 'https://api-gcp.binance.com/api/v3/ticker/price'

BINANCE_SYMBOLS = ['ETHUSDC', 'ETHUSDT', 'ETHDAI', 'USDCUSDT', 'USDTDAI',
                   'MATICUSDC', 'MATICETH', 'MATICUSDT', 'BTCUSDT', 'BTCUSDC', 'BTCDAI']

DEX_QUOTE_ASSETS = ['ETH', 'USDC', 'DAI', 'USDT', 'MATIC', 'USDC.E', 'BTC']

AVAILABLE_SUBNETS = ['MAINNET', 'TESTNET']
